import type { DashboardResponse } from "../models/loyalty.model";

export const DEMO_PHONE = "555-0100";

export const demoDashboard: DashboardResponse = {
  customerId: "customer-demo",
  phone: DEMO_PHONE,
  tier: {
    id: "member",
    name: "Member",
    bookingWindowDays: 7,
    pointRate: 1,
    perks: ["basic early access", "standard wash add-on"],
    description: "Demo loyalty account",
  },
  loyaltyTier: {
    id: "member",
    name: "Member",
    bookingWindowDays: 7,
    pointRate: 1,
    perks: ["basic early access", "standard wash add-on"],
    description: "Demo loyalty account",
  },
  pointsBalance: 184,
  vehicles: [{ plate: "ABC123", model: "Toyota Camry", type: "car" }],
  nextEligibleBookingDate: "2026-08-20",
  appliedPerks: ["standard wash add-on"],
  lateCancellationWarningCount: 0,
  priorityStatus: "normal",
  rewardSuggestions: [
    {
      id: "demo-reward-1",
      title: "Free tire shine",
      description: "Redeem points for a complimentary tire shine.",
      pointsRequired: 200,
      eligibleTiers: ["member"],
    },
  ],
  bookingHistory: [
    {
      id: "demo-upcoming-1",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Premium Exterior Wash",
      date: "2026-08-14",
      time: "10:00",
      points: 5,
      status: "confirmed",
      appliedPerks: ["standard wash add-on"],
    },
    {
      id: "demo-upcoming-2",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Interior Detail",
      date: "2026-08-15",
      time: "14:30",
      points: 8,
      status: "confirmed",
      appliedPerks: [],
    },
    {
      id: "demo-upcoming-3",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Quick Rinse",
      date: "2026-08-16",
      time: "09:00",
      points: 2,
      status: "confirmed",
      appliedPerks: [],
    },
    {
      id: "demo-history-1",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Gold Wash",
      date: "2026-08-09",
      time: "11:00",
      points: 10,
      status: "completed",
      appliedPerks: [],
    },
    {
      id: "demo-history-2",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Motorbike Wash",
      date: "2026-08-05",
      time: "15:00",
      points: 4,
      status: "cancelled",
      appliedPerks: [],
    },
  ],
  pointHistory: [
    {
      id: "demo-points-1",
      type: "earn",
      amount: 10,
      date: "2026-08-09",
      description: "Gold Wash completed",
    },
  ],
};
