import type {
  AdminBooking,
  DashboardResponse,
  GlobalPromotion,
  ClaimablePromo,
  ClaimedPromo,
} from "../models/loyalty.model";

export const DEMO_PHONE = "555-0100";

export const initialGlobalPromotions: GlobalPromotion[] = [
  {
    id: "global-prm-1",
    title: "Summer Splash: 20% Off All Washes",
    description: "Automatic 20% discount on every exterior package this week.",
    discountPercentage: 20,
    badgeLabel: "Featured Deal",
    validUntil: "Aug 31, 2026",
    isActive: true,
  },
  {
    id: "global-prm-2",
    title: "Free Tire Shine Weekend",
    description:
      "Complimentary tire dressing upgrade added to all weekend appointments.",
    badgeLabel: "Weekend Special",
    validUntil: "Aug 24, 2026",
    isActive: true,
  },
  {
    id: "global-prm-3",
    title: "Early Bird 15% Bonus Points",
    description:
      "Earn 15% extra loyalty points on appointments before 10:00 AM.",
    badgeLabel: "Loyalty Boost",
    validUntil: "Sep 15, 2026",
    isActive: true,
  },
];

export const initialClaimablePromos: ClaimablePromo[] = [
  // Silver Tier & Above
  {
    id: "prm-silver-1",
    title: "15% Off Detail",
    description:
      "15% discount voucher for complete interior or exterior detailing.",
    pointPrice: 300,
    requiredTier: "SILVER",
    tierGroup: "SILVER TIER & ABOVE",
    perkType: "detail-discount-15",
    validityDays: 30,
  },
  {
    id: "prm-silver-2",
    title: "Free Air Freshener",
    description:
      "Complimentary custom fragrance tree hanging in vehicle cabin.",
    pointPrice: 150,
    requiredTier: "SILVER",
    tierGroup: "SILVER TIER & ABOVE",
    perkType: "free-air-freshener",
    validityDays: 45,
  },

  // Gold Tier & Above
  {
    id: "prm-gold-1",
    title: "Free Nano Coating",
    description:
      "Complimentary nano polymer protective shield applied on finish.",
    pointPrice: 1000,
    requiredTier: "GOLD",
    tierGroup: "GOLD TIER & ABOVE",
    perkType: "nano-coating-shield",
    validityDays: 30,
  },
  {
    id: "prm-gold-2",
    title: "Priority Queue Pass",
    description:
      "Fast-track express bay priority ticket bypassing general queues.",
    pointPrice: 800,
    requiredTier: "GOLD",
    tierGroup: "GOLD TIER & ABOVE",
    perkType: "priority-queue-pass",
    validityDays: 60,
  },

  // Platinum Tier
  {
    id: "prm-platinum-1",
    title: "Ultimate Spa Wash",
    description:
      "Comprehensive 90-minute full restoration, machine glaze, and ozone treatment.",
    pointPrice: 2500,
    requiredTier: "PLATINUM",
    tierGroup: "PLATINUM TIER",
    perkType: "ultimate-spa-wash",
    validityDays: 90,
  },
];

export const initialClaimedPromos: ClaimedPromo[] = [
  {
    id: "claim-demo-1",
    promoId: "prm-member-std",
    title: "10% Off Standard",
    description: "10% discount off standard wash booking.",
    claimedAt: "2026-08-01T10:00:00Z",
    validUntil: "Oct 30",
    status: "ACTIVE",
    perkIdentifier: "standard-wash-10-off",
  },
  {
    id: "claim-demo-2",
    promoId: "prm-vac-free",
    title: "Free Vacuuming",
    description: "Complimentary interior vacuum add-on.",
    claimedAt: "2026-08-05T14:30:00Z",
    validUntil: "Nov 15",
    status: "ACTIVE",
    perkIdentifier: "free-vacuuming-addon",
  },
  {
    id: "claim-demo-3",
    promoId: "prm-tire-shine-old",
    title: "Free Tire Shine Voucher",
    description: "Seasonal tire dressing discount voucher.",
    claimedAt: "2026-06-01T10:00:00Z",
    validUntil: "Jul 15",
    status: "EXPIRED",
    perkIdentifier: "free-tire-shine-voucher",
  },
];

export const initialAdminBookings: AdminBooking[] = [
  {
    id: "BK-103607",
    customer: "Alex Harrison",
    phone: "555-0101",
    tier: "PLATINUM",
    vehicle: "Toyota Camry (29A-8821)",
    timeSlot: "Today 10:45 AM",
    services: "Platinum Signature Detail",
    status: "PENDING",
  },
  {
    id: "BK-106438",
    customer: "Jessica Taylor",
    phone: "555-0102",
    tier: "PLATINUM",
    vehicle: "Toyota RAV4 (30E-4412)",
    timeSlot: "Today 10:45 AM",
    services: "Hydro-Ceramic Coat Wash",
    status: "PENDING",
  },
  {
    id: "BK-109483",
    customer: "David Miller",
    phone: "555-0103",
    tier: "GOLD",
    vehicle: "Honda CR-V (29K-9122)",
    timeSlot: "Today 10:35 AM",
    services: "Deluxe Exterior & Wheel Clean",
    status: "PENDING",
  },
  {
    id: "BK-107524",
    customer: "Marcus Vance",
    phone: "555-0104",
    tier: "MEMBER",
    vehicle: "Ford Ranger (51C-1290)",
    timeSlot: "Today 10:45 AM",
    services: "Express Touchless",
    status: "CONFIRMED",
  },
  {
    id: "BK-107526",
    customer: "Elena Rostova",
    phone: "555-0105",
    tier: "PLATINUM",
    vehicle: "Audi A6 (30H-5555)",
    timeSlot: "Today 10:45 AM",
    services: "Premium Total Shine Package",
    status: "CONFIRMED",
  },
  {
    id: "BK-107527",
    customer: "William Chen",
    phone: "555-0106",
    tier: "SILVER",
    vehicle: "Mazda 3 (29D-7819)",
    timeSlot: "Today 10:35 AM",
    services: "Express Touchless + Tire Shine",
    status: "CONFIRMED",
  },
  {
    id: "BK-107912",
    customer: "Rachel Green",
    phone: "555-0107",
    tier: "GOLD",
    vehicle: "BMW 330i (30A-9012)",
    timeSlot: "Today 10:00 AM",
    services: "Deluxe Exterior + Interior Wipe",
    status: "COMPLETED",
  },
  {
    id: "BK-107533",
    customer: "Tom Walker",
    phone: "555-0108",
    tier: "MEMBER",
    vehicle: "Kia Seltos (29H-3145)",
    timeSlot: "Today 09:30 AM",
    services: "Basic Rinse & Run",
    status: "CANCELLED",
  },
];

export const demoDashboard: DashboardResponse = {
  customerId: "customer-demo",
  phone: DEMO_PHONE,
  username: "demo_user",
  tier: {
    id: "gold",
    name: "Gold",
    bookingWindowDays: 12,
    pointRate: 1.5,
    perks: ["gold priority booking", "free premium wax"],
    description: "Gold VIP loyalty account",
  },
  pointsBalance: 1500,
  vehicles: [{ plate: "ABC123", model: "Toyota Camry", type: "car" }],
  nextEligibleBookingDate: "2026-08-20",
  appliedPerks: ["standard wash add-on"],
  lateCancellationWarningCount: 0,
  priorityStatus: "normal",
  rewardSuggestions: [
    {
      id: "demo-reward-1",
      title: "Free tire shine",
      description: "Redeem points for a complimentary tire shine.",
      pointsRequired: 200,
      eligibleTiers: ["member"],
    },
  ],
  bookingHistory: [
    {
      id: "demo-upcoming-1",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Premium Exterior Wash",
      date: "2026-08-15",
      time: "10:00",
      points: 5,
      status: "confirmed",
      appliedPerks: ["standard wash add-on"],
    },
    {
      id: "demo-upcoming-2",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Interior Detail",
      date: "2026-08-15",
      time: "14:30",
      points: 8,
      status: "confirmed",
      appliedPerks: [],
    },
    {
      id: "demo-upcoming-3",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Quick Rinse",
      date: "2026-08-16",
      time: "09:00",
      points: 2,
      status: "confirmed",
      appliedPerks: [],
    },
    {
      id: "demo-history-1",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Gold Wash",
      date: "2026-08-09",
      time: "11:00",
      points: 10,
      status: "completed",
      appliedPerks: [],
    },
    {
      id: "demo-history-2",
      vehiclePlate: "ABC123",
      vehicleModel: "Toyota Camry",
      service: "Motorbike Wash",
      date: "2026-08-05",
      time: "15:00",
      points: 4,
      status: "cancelled",
      appliedPerks: [],
    },
  ],
  pointHistory: [
    {
      id: "demo-points-1",
      type: "earn",
      amount: 10,
      date: "2026-08-09",
      description: "Gold Wash completed",
    },
  ],
};
